filter:
  fixed_frame: 'track'
  pcl_frame: 'vehicle_blue/chassis/lidar'
  odom_topic: '/gazebo/odom'
  imu_topic: '/imu'   # does nothing
  pcl_topic: '/points'
vehicle:
  abs_pose: [17.4, 12.3, 1, 0, 0, 0]  #absolute position and rotation
  linear_speed_f: 0.75
  cmd_vel: '/model/cmd_vel'
lidar:
  pose: [-0.26, 0, 0.47, 0, 0.1570796, 0.0]  #lidar position and rotation relative to the car
  hz: 20
  h_samples: 900
  h_min_angle: -1.570796 #2.356194   #135째
  h_max_angle: 1.570796 #3.926991   #225째
  h_resolution: 0.1
  v_samples: 320
  v_min_angle: -0.4363323 #-25째
  v_max_angle: 0.2617994  #15째
  v_resolution: 0.1
  min_range: 0.01
  max_range: 80.0
  range_resolution: 0.01
  noise_mean: 0.0
  noise_std: 0.01
cones:
  min_dist: 2.5 #minimum distance between cones
  scale: 10 #map coordinates scale
  track_width: 4
